# Starting with Data with Pandas

In [1]:
# Author: Martin Callaghan
# Date: 2021-10-18
# Lesson link: https://arctraining.github.io/python-2021-04/02-starting-with-data/index.html

In [1]:
# Connect my Google Drive to Google Colab
from google.colab import drive
drive.mount ('/content/gdrive')

Mounted at /content/gdrive

In [2]:
# Change the working directory
%cd /content/gdrive/MyDrive/swd1a-python-2021-10

/content/gdrive/.shortcut-targets-by-id/1c-UzOKbLCZjy_P7oCGtvGKn-RoOvpDyC/swd1a-python-2021-10

In [3]:
# Check the working directory
!pwd

/content/gdrive/.shortcut-targets-by-id/1c-UzOKbLCZjy_P7oCGtvGKn-RoOvpDyC/swd1a-python-2021-10

In [ ]:
# We use the Portal Project teaching dataset
# https://figshare.com/articles/dataset/Portal_Project_Teaching_Database/1314459

In [ ]:
# But first we need to download it
!wget -O data.zip https://arctraining.github.io/python-2021-04/data/portal-teachingdb-master.zip

--2021-10-18 13:53:56--  https://arctraining.github.io/python-2021-04/data/portal-teachingdb-master.zip
Resolving arctraining.github.io (arctraining.github.io)... 185.199.108.153, 185.199.109.153, 185.199.110.153, ...
Connecting to arctraining.github.io (arctraining.github.io)|185.199.108.153|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 689547 (673K) [application/zip]
Saving to: ‘data.zip’

data.zip            100%[===================>] 673.39K  --.-KB/s    in 0.05s

2021-10-18 13:53:56 (14.0 MB/s) - ‘data.zip’ saved [689547/689547]

In [ ]:
# Check the contents of the current working directory
!ls -l

total 714
-rw------- 1 root root  35824 Oct 18 13:50 010_starting_with_python.ipynb
-rw------- 1 root root   4790 Oct 18 14:09 020_starting_with_data.ipynb
-rw------- 1 root root 689547 May 17 13:50 data.zip

In [ ]:
# Unzip the data.zip file
!unzip data.zip

Archive:  data.zip
   creating: portal-teachingdb-master/
  inflating: portal-teachingdb-master/surveys2001.csv
  inflating: portal-teachingdb-master/surveys2002.csv
  inflating: portal-teachingdb-master/speciesSubset.csv
  inflating: portal-teachingdb-master/bouldercreek_09_2013.txt
  inflating: portal-teachingdb-master/species.csv
  inflating: portal-teachingdb-master/surveys.csv
  inflating: portal-teachingdb-master/portal_mammals.sqlite
  inflating: portal-teachingdb-master/README.txt
  inflating: portal-teachingdb-master/plots.csv

In [4]:
# Check the contents of the current working directory
!ls -l

total 83
-rw------- 1 root root 35824 Oct 18 13:50 010_starting_with_python.ipynb
-rw------- 1 root root 44917 Oct 25 10:37 020_starting_with_data.ipynb
drwx------ 2 root root  4096 Oct 18 14:12 data

In [ ]:
# Rename the folder portal-teachingdb-master to data
!mv portal-teachingdb-master/ data/

In [ ]:
# Check the contents of the current working directory
!ls -l

total 721
-rw------- 1 root root  35824 Oct 18 13:50 010_starting_with_python.ipynb
-rw------- 1 root root   8066 Oct 18 14:12 020_starting_with_data.ipynb
drwx------ 2 root root   4096 Oct 18 14:12 data
-rw------- 1 root root 689547 May 17 13:50 data.zip

## Exploring the data

In [5]:
# import the pandas library
import pandas as pd

In [41]:
# First have a look at surveys.csv
pd.read_csv('data/surveys.csv')

       record_id  month  day  year  ...  species_id  sex hindfoot_length  weight
0              1      7   16  1977  ...          NL    M            32.0     NaN
1              2      7   16  1977  ...          NL    M            33.0     NaN
2              3      7   16  1977  ...          DM    F            37.0     NaN
3              4      7   16  1977  ...          DM    M            36.0     NaN
4              5      7   16  1977  ...          DM    M            35.0     NaN
...          ...    ...  ...   ...  ...         ...  ...             ...     ...
35544      35545     12   31  2002  ...          AH  NaN             NaN     NaN
35545      35546     12   31  2002  ...          AH  NaN             NaN     NaN
35546      35547     12   31  2002  ...          RM    F            15.0    14.0
35547      35548     12   31  2002  ...          DO    M            36.0    51.0
35548      35549     12   31  2002  ...         NaN  NaN             NaN     NaN

[35549 rows x 9 columns]

In [7]:
# Read in the df and assign it to a variable
surveys_df = pd.read_csv('data/surveys.csv')

In [8]:
# Quickly view the contents
surveys_df

       record_id  month  day  year  ...  species_id  sex hindfoot_length  weight
0              1      7   16  1977  ...          NL    M            32.0     NaN
1              2      7   16  1977  ...          NL    M            33.0     NaN
2              3      7   16  1977  ...          DM    F            37.0     NaN
3              4      7   16  1977  ...          DM    M            36.0     NaN
4              5      7   16  1977  ...          DM    M            35.0     NaN
...          ...    ...  ...   ...  ...         ...  ...             ...     ...
35544      35545     12   31  2002  ...          AH  NaN             NaN     NaN
35545      35546     12   31  2002  ...          AH  NaN             NaN     NaN
35546      35547     12   31  2002  ...          RM    F            15.0    14.0
35547      35548     12   31  2002  ...          DO    M            36.0    51.0
35548      35549     12   31  2002  ...         NaN  NaN             NaN     NaN

[35549 rows x 9 columns]

In [9]:
# Look at the first few rows
surveys_df.head(4)

   record_id  month  day  year  plot_id species_id sex  hindfoot_length  weight
0          1      7   16  1977        2         NL   M             32.0     NaN
1          2      7   16  1977        3         NL   M             33.0     NaN
2          3      7   16  1977        2         DM   F             37.0     NaN
3          4      7   16  1977        7         DM   M             36.0     NaN

In [10]:
# Look at the bottom few rows
surveys_df.tail(5)

       record_id  month  day  year  ...  species_id  sex hindfoot_length  weight
35544      35545     12   31  2002  ...          AH  NaN             NaN     NaN
35545      35546     12   31  2002  ...          AH  NaN             NaN     NaN
35546      35547     12   31  2002  ...          RM    F            15.0    14.0
35547      35548     12   31  2002  ...          DO    M            36.0    51.0
35548      35549     12   31  2002  ...         NaN  NaN             NaN     NaN

[5 rows x 9 columns]

In [11]:
# What type of thing is surveys_df
type (surveys_df)

pandas.core.frame.DataFrame

In [12]:
# What are the data types of the columns
surveys_df.dtypes

record_id            int64
month                int64
day                  int64
year                 int64
plot_id              int64
species_id          object
sex                 object
hindfoot_length    float64
weight             float64
dtype: object

In [13]:
# What are the columns
surveys_df.columns

Index(['record_id', 'month', 'day', 'year', 'plot_id', 'species_id', 'sex',
       'hindfoot_length', 'weight'],
      dtype='object')

In [14]:
# What is the shape (rows x columns)?
surveys_df.shape

(35549, 9)

In [15]:
# What are the unique values of the categorical data in species
pd.unique(surveys_df['species_id'])

array(['NL', 'DM', 'PF', 'PE', 'DS', 'PP', 'SH', 'OT', 'DO', 'OX', 'SS',
       'OL', 'RM', nan, 'SA', 'PM', 'AH', 'DX', 'AB', 'CB', 'CM', 'CQ',
       'RF', 'PC', 'PG', 'PH', 'PU', 'CV', 'UR', 'UP', 'ZL', 'UL', 'CS',
       'SC', 'BA', 'SF', 'RO', 'AS', 'SO', 'PI', 'ST', 'CU', 'SU', 'RX',
       'PB', 'PL', 'PX', 'CT', 'US'], dtype=object)

In [16]:
# Challenge 1: Stats
# What are the unique values of 'plot_id'
site_names = pd.unique(surveys_df['plot_id'])

In [17]:
site_names

array([ 2,  3,  7,  1,  6,  5,  8,  4, 11, 14, 15, 13,  9, 10, 17, 16, 20,
       23, 18, 21, 22, 19, 12, 24])

In [18]:
# How many unique plot_id are there?
pd.unique(surveys_df['plot_id']).shape

(24,)

In [19]:
len(site_names)

24

In [20]:
# How many unique species_id are there?
len(pd.unique(surveys_df['species_id']))

49

In [21]:
# What is the difference between running the commands 
# len(site_names) and 
# surveys_df['plot_id'].nunique()?

In [22]:
# Descriptive statistics of the dataframe
surveys_df['weight'].describe()

count    32283.000000
mean        42.672428
std         36.631259
min          4.000000
25%         20.000000
50%         37.000000
75%         48.000000
max        280.000000
Name: weight, dtype: float64

In [23]:
# If I wanted just a single metric
surveys_df['weight'].max()

280.0

In [24]:
surveys_df['weight'].mean()

42.672428212991356

In [25]:
# If we wanted to summarise by one or more variables, for example sex, we can use
# the groupby method in pandas.

In [26]:
# group the data by sex
grouped_data = surveys_df.groupby('sex')

In [27]:
# Summary stats
grouped_data.describe()

    record_id                                   ... weight
        count          mean           std  min  ...    25%   50%   75%    max
sex                                             ...
F     15690.0  18036.412046  10423.089000  3.0  ...   20.0  34.0  46.0  274.0
M     17348.0  17754.835601  10132.203323  1.0  ...   20.0  39.0  49.0  280.0

[2 rows x 56 columns]

In [28]:
# But just the mean values
grouped_data.mean()

        record_id     month        day  ...    plot_id  hindfoot_length     weight
sex                                     ...
F    18036.412046  6.587253  15.880943  ...  11.440854        28.836780  42.170555
M    17754.835601  6.396184  16.078799  ...  11.098282        29.709578  42.995379

[2 rows x 7 columns]

### Challenge 2: summary data

1. How many recorded individuals are female `F` and how many male `M`?
2. What happens when you group by two columns using the following syntax and then calculate mean values?
* grouped_data2 = surveys_df.groupby(['plot_id', 'sex'])
* grouped_data2.mean()
3. Summarise weight values for each site in your data. HINT: you can use the following syntax to only create summary statistics for one column in your data. by_site['weight'].describe()

In [32]:
grouped_data.count()

     record_id  month    day  ...  species_id  hindfoot_length  weight
sex                           ...
F        15690  15690  15690  ...       15690            14894   15303
M        17348  17348  17348  ...       17348            16476   16879

[2 rows x 8 columns]

In [34]:
grouped_data2 = surveys_df.groupby(['plot_id', 'sex'])
grouped_data2.mean()

                record_id     month  ...  hindfoot_length     weight
plot_id sex                          ...
1       F    18390.384434  6.597877  ...        31.733911  46.311138
        M    17197.740639  6.121461  ...        34.302770  55.950560
2       F    17714.753608  6.426804  ...        30.161220  52.561845
        M    18085.458042  6.340035  ...        30.353760  51.391382
3       F    19888.783875  6.610302  ...        23.774044  31.215349
        M    20226.767857  6.277381  ...        23.833744  34.163241
4       F    17489.205275  6.447248  ...        33.249102  46.818824
        M    18493.841748  6.436893  ...        34.097959  48.888119
5       F    12280.793169  6.142315  ...        28.921844  40.974806
        M    12798.426621  6.194539  ...        29.694794  40.708551
6       F    19406.503392  6.640434  ...        26.981322  36.352288
        M    17849.574607  6.043194  ...        27.425591  36.867388
7       F    19069.668657  6.385075  ...        19.779553  20.006135
        M    19188.729642  6.719870  ...        20.536667  21.194719
8       F    18920.276190  6.644048  ...        32.187578  45.623011
        M    19452.109868  6.585961  ...        33.751059  49.641372
9       F    16217.497069  6.507620  ...        35.126092  53.618469
        M    18000.710159  6.369522  ...        34.175732  49.519309
10      F    16001.496454  5.588652  ...        18.641791  17.094203
        M    15708.704225  5.718310  ...        19.567164  19.971223
11      F    16994.962287  6.770073  ...        32.029299  43.515075
        M    16933.909621  6.379981  ...        32.078014  43.366197
12      F    17457.966981  6.509434  ...        30.975124  49.831731
        M    17592.327500  6.304167  ...        31.762489  48.909710
13      F    18033.100318  6.815287  ...        27.201014  40.524590
        M    16969.044700  6.485313  ...        27.893793  40.097754
14      F    17097.145275  6.519041  ...        32.973373  47.355491
        M    17891.948598  6.666355  ...        32.961802  45.159378
15      F    20602.449064  6.582121  ...        21.949891  26.670236
        M    18104.019560  6.193154  ...        21.803109  27.523691
16      F    19002.445946  6.369369  ...        23.144928  25.810427
        M    18434.714286  6.208791  ...        23.480916  23.811321
17      F    18234.322870  6.650224  ...        30.918536  48.176201
        M    18857.651472  6.569801  ...        32.227634  47.558853
18      F    17940.875497  6.698013  ...        26.690341  36.963514
        M    15106.718850  6.610224  ...        27.703072  43.546952
19      F    21848.216475  6.701149  ...        21.257937  21.978599
        M    19470.779690  6.533563  ...        21.071685  20.306878
20      F    17510.769231  6.743077  ...        27.069193  52.624406
        M    16076.192496  6.489396  ...        27.908451  44.197279
21      F    22452.636661  6.860884  ...        22.366554  25.974832
        M    20120.399113  6.671840  ...        21.736721  22.772622
22      F    18499.695976  6.651267  ...        34.108320  53.647059
        M    18015.365527  6.381872  ...        33.359746  54.572531
23      F    15863.193939  6.860606  ...        20.051948  20.564417
        M    17091.338164  6.391304  ...        19.850000  18.941463
24      F    13702.224280  6.596708  ...        26.993377  47.914405
        M    15208.136082  6.360825  ...        25.786996  39.321503

[48 rows x 6 columns]

In [35]:
by_site = surveys_df.groupby(['plot_id'])
by_site['weight'].describe()

          count       mean        std  min   25%   50%   75%    max
plot_id
1        1903.0  51.822911  38.176670  4.0  30.0  44.0  53.0  231.0
2        2074.0  52.251688  46.503602  5.0  24.0  41.0  50.0  278.0
3        1710.0  32.654386  35.641630  4.0  14.0  23.0  36.0  250.0
4        1866.0  47.928189  32.886598  4.0  30.0  43.0  50.0  200.0
5        1092.0  40.947802  34.086616  5.0  21.0  37.0  48.0  248.0
6        1463.0  36.738893  30.648310  5.0  18.0  30.0  45.0  243.0
7         638.0  20.663009  21.315325  4.0  11.0  17.0  23.0  235.0
8        1781.0  47.758001  33.192194  5.0  26.0  44.0  51.0  178.0
9        1811.0  51.432358  33.724726  6.0  36.0  45.0  50.0  275.0
10        279.0  18.541219  20.290806  4.0  10.0  12.0  21.0  237.0
11       1793.0  43.451757  28.975514  5.0  26.0  42.0  48.0  212.0
12       2219.0  49.496169  41.630035  6.0  26.0  42.0  50.0  280.0
13       1371.0  40.445660  34.042767  5.0  20.5  33.0  45.0  241.0
14       1728.0  46.277199  27.570389  5.0  36.0  44.0  49.0  222.0
15        869.0  27.042578  35.178142  4.0  11.0  18.0  26.0  259.0
16        480.0  24.585417  17.682334  4.0  12.0  20.0  34.0  158.0
17       1893.0  47.889593  35.802399  4.0  27.0  42.0  50.0  216.0
18       1351.0  40.005922  38.480856  5.0  17.5  30.0  44.0  256.0
19       1084.0  21.105166  13.269840  4.0  11.0  19.0  27.0  139.0
20       1222.0  48.665303  50.111539  5.0  17.0  31.0  47.0  223.0
21       1029.0  24.627794  21.199819  4.0  10.0  22.0  31.0  190.0
22       1298.0  54.146379  38.743967  5.0  29.0  42.0  54.0  212.0
23        369.0  19.634146  18.382678  4.0  10.0  14.0  23.0  199.0
24        960.0  43.679167  45.936588  4.0  19.0  27.5  45.0  251.0

In [36]:


    What happens when you execute:
        

    What happens when you call:
        surveys_df.iloc[0:4, 1:4]
        surveys_df.loc[0:4, 1:4]

    How are the two commands different?

IndentationError: ignored

In [38]:

surveys_df[:-1]

       record_id  month  day  year  ...  species_id  sex hindfoot_length  weight
0              1      7   16  1977  ...          NL    M            32.0     NaN
1              2      7   16  1977  ...          NL    M            33.0     NaN
2              3      7   16  1977  ...          DM    F            37.0     NaN
3              4      7   16  1977  ...          DM    M            36.0     NaN
4              5      7   16  1977  ...          DM    M            35.0     NaN
...          ...    ...  ...   ...  ...         ...  ...             ...     ...
35543      35544     12   31  2002  ...          US  NaN             NaN     NaN
35544      35545     12   31  2002  ...          AH  NaN             NaN     NaN
35545      35546     12   31  2002  ...          AH  NaN             NaN     NaN
35546      35547     12   31  2002  ...          RM    F            15.0    14.0
35547      35548     12   31  2002  ...          DO    M            36.0    51.0

[35548 rows x 9 columns]

In [39]:
surveys_df.loc[0:4, 1:4]

TypeError: ignored

In [43]:
survey_df_test = surveys_df.copy()

In [44]:
survey_df_test.columns[0:3] = [0, 1, 2]

TypeError: ignored